# Generated by Django 5.2.17 on 2026-09-29 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeParseJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('parsing', 'Parsing'), ('ready_for_review', 'Ready for review'), ('applied', 'Applied'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('result', models.JSONField(blank=True, null=True)),
                ('model', models.CharField(blank=True, max_length=100)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('error_code', models.CharField(blank=True, max_length=50)),
                ('error_message', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parse_jobs', to='documents.candidatedocument')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
