# Generated by Django 5.2.17 on 2026-10-01 02:06

import apps.ai_profile.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False)),
                ('token', models.CharField(default=apps.ai_profile.models.new_token, max_length=64, unique=True)),
                ('token_created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('visible_sections', models.JSONField(default=apps.ai_profile.models.default_visible_sections)),
                ('chatbot_enabled', models.BooleanField(default=True)),
                ('matching_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employer_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProfileAccessEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('view', 'Profile viewed'), ('chat_session', 'Chat started'), ('match', 'Job match requested')], max_length=20)),
                ('ip_hash', models.CharField(max_length=64)),
                ('user_agent', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_events', to='ai_profile.employerprofile')),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
            },
        ),
    ]
