# Generated by Django 5.2.17 on 2026-10-01 03:13

import apps.ai_profile.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_profile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobMatchRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(default=apps.ai_profile.models.new_match_id, max_length=32, unique=True)),
                ('source', models.CharField(choices=[('employer_profile', 'Employer'), ('candidate_self', 'Self-check')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('done', 'Done'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('jd_hash', models.CharField(max_length=64)),
                ('profile_fingerprint', models.CharField(max_length=64)),
                ('ip_hash', models.CharField(blank=True, max_length=64)),
                ('job_title', models.CharField(blank=True, max_length=200)),
                ('requirements', models.JSONField(blank=True, default=list)),
                ('score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('summary', models.JSONField(blank=True, default=dict)),
                ('model', models.CharField(blank=True, max_length=100)),
                ('error_code', models.CharField(blank=True, max_length=50)),
                ('error_message', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='ai_profile.employerprofile')),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
                'indexes': [models.Index(fields=['profile', 'jd_hash', 'profile_fingerprint'], name='ai_profile__profile_ad8da8_idx')],
            },
        ),
    ]
