# Generated by Django 5.2.17 on 2026-10-01 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_profile', '0002_job_match'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobmatchrequest',
            name='source_types',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobmatchrequest',
            name='source',
            field=models.CharField(choices=[('employer_profile', 'Employer'), ('website', 'Website visitor'), ('candidate_self', 'Self-check')], max_length=20),
        ),
    ]
