# Generated by Django 5.2.17 on 2026-10-03 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_profile', '0003_jobmatchrequest_source_types_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employerprofile',
            name='admin_disabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='admin_disabled_reason',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
