# Generated by Django 5.2.17 on 2026-10-01 17:37

import apps.websites.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(blank=True, max_length=40, null=True, unique=True)),
                ('template', models.CharField(default='modern', max_length=20)),
                ('theme', models.JSONField(default=apps.websites.models._default_theme)),
                ('sections', models.JSONField(default=apps.websites.models._default_sections)),
                ('overrides', models.JSONField(default=apps.websites.models._default_overrides)),
                ('bio_text', models.TextField(blank=True)),
                ('bio_source', models.CharField(blank=True, choices=[('candidate', 'Written by the candidate'), ('ai', 'AI draft, approved by the candidate')], max_length=10)),
                ('bio_approved_at', models.DateTimeField(blank=True, null=True)),
                ('bio_draft_status', models.CharField(blank=True, choices=[('', 'None'), ('pending', 'Pending'), ('done', 'Done'), ('failed', 'Failed')], max_length=10)),
                ('bio_draft_text', models.TextField(blank=True)),
                ('bio_draft_requested_at', models.DateTimeField(blank=True, null=True)),
                ('show_chatbot', models.BooleanField(default=True)),
                ('show_matching', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='website', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PreviewToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default=apps.websites.models.new_preview_token, max_length=64, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preview_tokens', to='websites.website')),
            ],
        ),
        migrations.CreateModel(
            name='WebsiteEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('preview_opened', 'Preview opened'), ('published', 'Published'), ('unpublished', 'Unpublished'), ('public_view', 'Public view')], max_length=20)),
                ('ip_hash', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='websites.website')),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='WebsiteVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('template', models.CharField(max_length=20)),
                ('data', models.JSONField()),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='websites.website')),
            ],
            options={
                'ordering': ['-number'],
            },
        ),
        migrations.AddField(
            model_name='website',
            name='published_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='websites.websiteversion'),
        ),
        migrations.AddConstraint(
            model_name='websiteversion',
            constraint=models.UniqueConstraint(fields=('website', 'number'), name='unique_version_number'),
        ),
    ]
