# Generated by Django 5.2.17 on 2026-10-03 04:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=20, unique=True)),
                ('enabled', models.BooleanField(default=True)),
                ('premium', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=60)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('default_sections', models.JSONField(default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='website',
            name='admin_blocked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='website',
            name='admin_blocked_reason',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.CreateModel(
            name='TemplateCatalogVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(unique=True)),
                ('data', models.JSONField()),
                ('note', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-number'],
            },
        ),
    ]
