# Generated by Django 5.2.17 on 2026-09-30 05:53

import django.db.models.deletion
import pgvector.django.indexes
import pgvector.django.vector
from django.conf import settings
from django.db import migrations, models
from pgvector.django import VectorExtension


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        VectorExtension(),
        migrations.CreateModel(
            name='KnowledgeBaseState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('idle', 'Idle'), ('indexing', 'Indexing'), ('ready', 'Ready'), ('failed', 'Failed')], default='idle', max_length=20)),
                ('chunk_count', models.PositiveIntegerField(default=0)),
                ('indexed_at', models.DateTimeField(blank=True, null=True)),
                ('error_code', models.CharField(blank=True, max_length=50)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_base_state', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='KnowledgeChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100)),
                ('source_type', models.CharField(choices=[('profile', 'Profile'), ('experience', 'Experience'), ('project', 'Project'), ('education', 'Education'), ('certification', 'Certification'), ('achievement', 'Achievement'), ('skills', 'Skills'), ('note', 'Note')], max_length=20)),
                ('source_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('text', models.TextField()),
                ('content_hash', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_chunks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ChunkEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=100)),
                ('embedding', pgvector.django.vector.VectorField(dimensions=1024)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chunk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='embeddings', to='knowledge_base.knowledgechunk')),
            ],
        ),
        migrations.AddIndex(
            model_name='knowledgechunk',
            index=models.Index(fields=['owner', 'source_type'], name='knowledge_b_owner_i_2eebe5_idx'),
        ),
        migrations.AddConstraint(
            model_name='knowledgechunk',
            constraint=models.UniqueConstraint(fields=('owner', 'key'), name='unique_chunk_key_per_owner'),
        ),
        migrations.AddIndex(
            model_name='chunkembedding',
            index=pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['embedding'], m=16, name='chunk_embedding_hnsw', opclasses=['vector_cosine_ops']),
        ),
        migrations.AddConstraint(
            model_name='chunkembedding',
            constraint=models.UniqueConstraint(fields=('chunk', 'model'), name='unique_embedding_per_model'),
        ),
    ]
