# Generated by Django 5.2.17 on 2026-09-30 07:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionGeneration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('full', 'Full set'), ('more', 'More questions')], max_length=10)),
                ('scope', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('done', 'Done'), ('failed', 'Failed')], db_index=True, default='pending', max_length=10)),
                ('sections', models.JSONField(default=list)),
                ('completed_sections', models.JSONField(default=list)),
                ('source_hash', models.CharField(blank=True, max_length=64)),
                ('model', models.CharField(blank=True, max_length=100)),
                ('error_code', models.CharField(blank=True, max_length=50)),
                ('error_message', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_generations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('section', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[('general', 'General'), ('technical', 'Technical'), ('experience', 'Experience'), ('project', 'Project'), ('behavioral', 'Behavioral'), ('domain', 'Domain')], max_length=20)),
                ('difficulty', models.CharField(choices=[('foundational', 'Foundational'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=20)),
                ('topic', models.CharField(blank=True, max_length=200)),
                ('text', models.TextField()),
                ('source_refs', models.JSONField(default=list)),
                ('talking_points', models.JSONField(default=list)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='follow_ups', to='questions.question')),
                ('generation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='questions.questiongeneration')),
            ],
            options={
                'ordering': ['order', 'pk'],
                'indexes': [models.Index(fields=['owner', 'is_active', 'category'], name='questions_q_owner_i_9dfaf3_idx')],
            },
        ),
    ]
