# Generated by Django 5.2.17 on 2026-09-30 04:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=200)),
                ('headline', models.CharField(blank=True, max_length=200)),
                ('summary', models.TextField(blank=True)),
                ('email', models.CharField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='documents.candidatedocument')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CandidateLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('source_type', models.CharField(choices=[('resume', 'Resume'), ('candidate_input', 'Candidate input')], default='candidate_input', max_length=20)),
                ('label', models.CharField(blank=True, max_length=100)),
                ('url', models.CharField(max_length=500)),
                ('source_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='documents.candidatedocument')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='candidates.candidateprofile')),
            ],
            options={
                'ordering': ['order', 'pk'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CandidateExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('source_type', models.CharField(choices=[('resume', 'Resume'), ('candidate_input', 'Candidate input')], default='candidate_input', max_length=20)),
                ('company', models.CharField(blank=True, max_length=200)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('start_date', models.CharField(blank=True, max_length=50)),
                ('end_date', models.CharField(blank=True, max_length=50)),
                ('is_current', models.BooleanField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('responsibilities', models.JSONField(blank=True, default=list)),
                ('achievements', models.JSONField(blank=True, default=list)),
                ('technologies', models.JSONField(blank=True, default=list)),
                ('source_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='documents.candidatedocument')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='candidates.candidateprofile')),
            ],
            options={
                'ordering': ['order', 'pk'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CandidateEducation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('source_type', models.CharField(choices=[('resume', 'Resume'), ('candidate_input', 'Candidate input')], default='candidate_input', max_length=20)),
                ('institution', models.CharField(blank=True, max_length=200)),
                ('degree', models.CharField(blank=True, max_length=200)),
                ('field_of_study', models.CharField(blank=True, max_length=200)),
                ('start_date', models.CharField(blank=True, max_length=50)),
                ('end_date', models.CharField(blank=True, max_length=50)),
                ('grade', models.CharField(blank=True, max_length=100)),
                ('source_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='documents.candidatedocument')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='candidates.candidateprofile')),
            ],
            options={
                'ordering': ['order', 'pk'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CandidateCertification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('source_type', models.CharField(choices=[('resume', 'Resume'), ('candidate_input', 'Candidate input')], default='candidate_input', max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('issuer', models.CharField(blank=True, max_length=200)),
                ('issue_date', models.CharField(blank=True, max_length=50)),
                ('expiry_date', models.CharField(blank=True, max_length=50)),
                ('credential_id', models.CharField(blank=True, max_length=200)),
                ('url', models.CharField(blank=True, max_length=500)),
                ('source_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='documents.candidatedocument')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='candidates.candidateprofile')),
            ],
            options={
                'ordering': ['order', 'pk'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CandidateAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('source_type', models.CharField(choices=[('resume', 'Resume'), ('candidate_input', 'Candidate input')], default='candidate_input', max_length=20)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('date', models.CharField(blank=True, max_length=50)),
                ('source_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='documents.candidatedocument')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='candidates.candidateprofile')),
            ],
            options={
                'ordering': ['order', 'pk'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CandidateProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('source_type', models.CharField(choices=[('resume', 'Resume'), ('candidate_input', 'Candidate input')], default='candidate_input', max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('role', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('technologies', models.JSONField(blank=True, default=list)),
                ('url', models.CharField(blank=True, max_length=500)),
                ('start_date', models.CharField(blank=True, max_length=50)),
                ('end_date', models.CharField(blank=True, max_length=50)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='candidates.candidateprofile')),
                ('source_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='documents.candidatedocument')),
            ],
            options={
                'ordering': ['order', 'pk'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CandidateSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('source_type', models.CharField(choices=[('resume', 'Resume'), ('candidate_input', 'Candidate input')], default='candidate_input', max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='candidates.candidateprofile')),
                ('source_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='documents.candidatedocument')),
            ],
            options={
                'ordering': ['order', 'pk'],
                'abstract': False,
            },
        ),
    ]
