# Generated by Django 5.2.17 on 2026-10-02 01:44

import apps.payments.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('price_amount', models.PositiveIntegerField()),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('entitlements', models.JSONField(default=list)),
                ('features', models.JSONField(default=list, help_text='Human-readable feature list for the pricing page')),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(default=apps.payments.models.new_public_id, max_length=32, unique=True)),
                ('provider', models.CharField(max_length=20)),
                ('provider_order_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('provider_payment_id', models.CharField(blank=True, db_index=True, max_length=100)),
                ('amount', models.PositiveIntegerField()),
                ('currency', models.CharField(max_length=3)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('initiated', 'Initiated'), ('successful', 'Successful'), ('failed', 'Failed'), ('refunded', 'Refunded'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20)),
                ('refunded_amount', models.PositiveIntegerField(default=0)),
                ('failure_reason', models.CharField(blank=True, max_length=300)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('last_reconciled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='payments.product')),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=20)),
                ('event_id', models.CharField(max_length=100)),
                ('event_type', models.CharField(max_length=60)),
                ('payload_sha256', models.CharField(max_length=64)),
                ('outcome', models.CharField(blank=True, max_length=60)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('provider', 'event_id'), name='unique_webhook_event')],
            },
        ),
        migrations.CreateModel(
            name='Entitlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('website_publish', 'Publish website'), ('premium_templates', 'Premium templates'), ('website_download', 'Download website'), ('employer_ai_profile', 'Employer AI profile'), ('priority_support', 'Priority support')], max_length=40)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entitlements', to=settings.AUTH_USER_MODEL)),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entitlements', to='payments.payment')),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('revoked_at__isnull', True)), fields=('user', 'code'), name='one_active_entitlement_per_code')],
            },
        ),
    ]
