# Generated by Django 5.2.17 on 2026-10-01 03:08

import apps.chatbot.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ai_profile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployerChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(default=apps.chatbot.models.new_session_id, max_length=32, unique=True)),
                ('ip_hash', models.CharField(max_length=64)),
                ('question_count', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_sessions', to='ai_profile.employerprofile')),
            ],
            options={
                'ordering': ['-last_activity', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='EmployerChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'Employer'), ('assistant', 'Assistant')], max_length=10)),
                ('content', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('done', 'Done'), ('failed', 'Failed')], default='done', max_length=10)),
                ('answer_status', models.CharField(blank=True, choices=[('answered', 'Answered'), ('not_found', 'Not in profile'), ('declined', 'Declined')], max_length=10)),
                ('citations', models.JSONField(blank=True, default=list)),
                ('model', models.CharField(blank=True, max_length=100)),
                ('error_code', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chatbot.employerchatsession')),
            ],
            options={
                'ordering': ['created_at', 'pk'],
            },
        ),
    ]
