# Generated by Django 5.2.17 on 2026-10-01 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employerchatsession',
            name='channel',
            field=models.CharField(choices=[('employer_profile', 'Employer profile'), ('website', 'Website')], default='employer_profile', max_length=20),
        ),
        migrations.AddField(
            model_name='employerchatsession',
            name='source_types',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
